#!/bin/bash

# extract memory arg to pass to JVM
megabytes=1024
for arg ; do
    if [ "$megabytes" = X ]; then
        megabytes=$arg
        break
    fi
    if [ "$arg" = "-m" ]; then
        megabytes=X
    fi
done
if [ "$megabytes" = X ]; then
    megabytes=1024
fi

# add all jar files in lib to classpath
THE_CLASSPATH=dist/icfp2015.jar
for i in `ls ./lib/*.jar`
do
  THE_CLASSPATH=${THE_CLASSPATH}:${i}
done

java -Xmx${megabytes}m -cp ${THE_CLASSPATH} main/Main "$@"
